# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
