# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0005_auto_20170925_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.RemoveField(
            model_name='record',
            name='amount',
        ),
        migrations.AddField(
            model_name='record',
            name='address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='record',
            name='afternoonTimeSlot',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='clinicName',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='record',
            name='eveningTimeSlot',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='mobile',
            field=models.CharField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='record',
            name='morningTimeSlot',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='services',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='record',
            name='specialization',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
