# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0007_auto_20170925_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={},
        ),
        migrations.AlterField(
            model_name='record',
            name='services',
            field=models.CharField(choices=[('1', 'Skin Checks'), ('2', 'Hair Loss Treatment'), ('3', 'Tatoo Removal')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='specialization',
            field=models.CharField(choices=[('2', 'Dentist'), ('1', 'General Physician')], default='1', max_length=1, null=True),
        ),
    ]
