# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0008_auto_20170925_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='afternoonTimeSlot',
        ),
        migrations.RemoveField(
            model_name='record',
            name='eveningTimeSlot',
        ),
        migrations.RemoveField(
            model_name='record',
            name='morningTimeSlot',
        ),
        migrations.AddField(
            model_name='record',
            name='afternoonTimeSlotEnd',
            field=models.TimeField(null=True, verbose_name='Afternoon Time Slot End'),
        ),
        migrations.AddField(
            model_name='record',
            name='afternoonTimeSlotStart',
            field=models.TimeField(null=True, verbose_name='Afternoon Time Slot Start'),
        ),
        migrations.AddField(
            model_name='record',
            name='eveningTimeSlotEnd',
            field=models.TimeField(null=True, verbose_name='Evening Time Slot End'),
        ),
        migrations.AddField(
            model_name='record',
            name='eveningTimeSlotStart',
            field=models.TimeField(null=True, verbose_name='Evening Time Slot Start'),
        ),
        migrations.AddField(
            model_name='record',
            name='morningTimeSlotEnd',
            field=models.TimeField(null=True, verbose_name='Morning Time Slot End'),
        ),
        migrations.AddField(
            model_name='record',
            name='morningTimeSlotStart',
            field=models.TimeField(null=True, verbose_name='Morning Time Slot Start'),
        ),
    ]
