# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_auto_20170925_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='afternoonTimeSlotEnd',
            field=models.TimeField(null=True, verbose_name='Afternoon Slot End Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='afternoonTimeSlotStart',
            field=models.TimeField(null=True, verbose_name='Afternoon Slot Start Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='eveningTimeSlotEnd',
            field=models.TimeField(null=True, verbose_name='Evening Slot End Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='eveningTimeSlotStart',
            field=models.TimeField(null=True, verbose_name='Evening Slot Start Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='morningTimeSlotEnd',
            field=models.TimeField(null=True, verbose_name='Morning Slot End Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='morningTimeSlotStart',
            field=models.TimeField(null=True, verbose_name='Morning Slot Start Time'),
        ),
    ]
