# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0010_auto_20170925_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='afternoonTimeSlotEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='Afternoon Slot End Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='afternoonTimeSlotStart',
            field=models.TimeField(blank=True, null=True, verbose_name='Afternoon Slot Start Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='eveningTimeSlotEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='Evening Slot End Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='eveningTimeSlotStart',
            field=models.TimeField(blank=True, null=True, verbose_name='Evening Slot Start Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='morningTimeSlotEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='Morning Slot End Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='morningTimeSlotStart',
            field=models.TimeField(blank=True, null=True, verbose_name='Morning Slot Start Time'),
        ),
    ]
