# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0011_auto_20170925_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Doctor Info', 'verbose_name_plural': 'Doctors List'},
        ),
    ]
